#apiVersion: v1
#kind: ConfigMap 
#metadata:
#  name: web-config 
#data:
#  DB_USER: "postgres"
#  DB_PASSWORD: "postgres"
#  DB_HOST: "database-1.cluster-cjo2qwqge1cu.ap-south-1.rds.amazonaws.com"
#  DB_PORT: "5432"
#  DB_NAME: "postgres"

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: attendance-app
  
data:
  DB_USER: "postgresadmin"
  DB_HOST: "172.17.0.2" 
  DB_PORT: "7001"
  DB_NAME: "postgres"

