apiVersion: apps/v1 
kind: Deployment
metadata:
  name: attendance-app 
  namespace: attendance-app
  labels:
    app: attendance-app 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: attendance-app

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  

  template:
    metadata:
      labels:
        app: attendance-app
    spec:
      containers:
        - name: attendance-app-container 
          image: chimuanyavic7/attendance-app:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: db-secrets  

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3           
                
      


