apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secrets
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgASoZ6q7ILqQiCyhwWJxSoQq22WUblwkBuVcr4muRsW0/4QJphNeLpIHLW1RQxNWGALCnrloaC1e/SGtLFrjPFu157hGvNNMyGZTBK2mtr7xewdA1QhoC4kgqDwYDGm9pYkOKzLCzmGvoNBnFQvrIR/JNVEZXTuaMQ0Ho0dwZiXyIxP6J0rgcnztB+naVZHcWlFqQuU06Widw4vX4+xce9E8yr5SxFY8F6ahZr9MwqUZ0pC3t97YiqDc3t5xmhiKTr/k2O2cmy1s/xzHKEu0eDe1A621KHpqINrKxj75VobND+3Y46J41tHN1fQHYVFb6wRi4s0FUd8qBqHhs5b/uoWqUd3SEStIMa9Ycw+mBnO8OZM/YRmcDkAgk4ujiJhDVQah13baQWJwHOK2Twjqa/buRp0KpA6hIpi/V/GAqItUbcPZNyHo38bZ8i9sgT4kLZ+RRKiol56lGOqqWOQVGqQJrH5gSHb8l+YxEefRsGQjfhpZjTzyDay2E6N3H8UVHRo9LN3UgRy6wRf0bY5qqgkiPF86E/ih/JLkcZUFek6qBgzTIsov68/l3Vp3Np40kgyZUHYmYBX5tvRO7gwXEBElmi/2nPKQlf7LEXvzlzE4a+i1QoUf5BmeBHwoOZyYH3/8BLntjNoZcF1BLBQKzDK+IdBl2Pczk4dCCmSNHvtJbSrAfwAcqqgqvEPPA1dGj56BRRcwGL4dWMbaA==
  template:
    metadata:
      name: db-secrets
      namespace: default

