apiVersion: v1
kind: Service
metadata:
  name: attendanceapp-service
  namespace: attendance-app
spec:
  type: NodePort
  selector:
    app: attendance-app
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
