---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.dbSecretName }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    DB_PASSWORD: {{ .Values.DB_PASSWORD }} 
  template:
    metadata:
      name: {{ .Values.dbSecretName }}
      namespace: {{ .Values.namespace }}
