apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace:  {{ .Values.namespace }}
  labels:
    app: {{ .Values.label }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.label }}


  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  

  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
        - name: "{{ .Values.deployment.name }}-container"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.name }}
            - secretRef:
                name: {{ .Values.dbSecretName }}
      
      resources:
        requests:
          cpu: "{{ .Values.resources.requests.cpu }}"
          memory: "{{ .Values.resources.requests.memory }}"
        limits:
          cpu: "{{ .Values.resources.limits.cpu }}"
          memory: "{{ .Values.resources.limits.memory }}"

      livenessProbe:
        httpGet:
          path: /api/health
          port: 5000
        initialDelaySeconds: 30
        periodSeconds: 15
        timeoutSeconds: 5

      readinessProbe:
        httpGet:
          path: /api/health
          port: 5000
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 3      

           


