deployment:
  name: attendance-app
  namespace: attendance-app
  containerPort: 5000

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2

label: attendance-app

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: chimuanyavic7/attendance-app
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.1"



# Project namespace for your application
namespace: attendance-app

dbSecretName: db-secrets

dbPassword: AgBYI2YtdSejuy/txU3X3gzH3L+B+gLo9SiM6SbKrPaZMDlifrGezdjoDzx6AcEqhRV1nhecGJmj4t6gdFiktkVNhbJnVk2qxdWIXUiuvoLO31IUQSVAsa1IRlLiQYQuZAdsL5H/zUjAowWrLPwXcV/Q/ZcZQtsMfPQFHDu279BIThIie/0QPl/8wWJox/PoDtNOe21L9yPdXOmB9/e0twzsyhlsI/goPoLXJbIe5YnG0Tm9gianRrrPwoDQIUe00+62lHS/4XE92hkiv1sE8ceT3r6ELWiVNzZ97cv3qMd+T6vh9MPMF5uAhFplIXS8GsL2QmmNTQCiCgnHcBrVPUHZHt9Yuu9GAgRcIbgu2W8zAWT5TxK8hAOVIq+6CAtirn8rjWQnEoNWsS+0Om3GV+xMM9zkhbrViQiheVBEiQBMYkDBgQESZs4uisBvRkGcriTg5CYnAgOI2BhD3RxYYixiyB1GLd05D8OR1zGKvcFY/y/VhuMxJOiUjIefJa5kMxM4za5YscmqBFPxtYD5CV4WLWAvjivavLj94p6OhwQuS+Lrwj7BdpiA3w7cXrpjkzUbCvZO9CEl4BFqxdTkaRWm61voqM77zOQkKe/I3TvNiAr+4vXMgGTwdyyqye9s63alptWF1WdNNVNgvSLHtSq4KYlyrdDlD7dqAUnMSakNAIxEHPBnfE50F4FaDMyyumD2v49MdLvRDQ==

config:
  name: db-config
  DB_USER: "admin"
  DB_HOST: "172.17.0.2" 
  DB_PORT: "7001"
  DB_NAME: "postgres"

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  name: attendance-app-service
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: NodePort
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 5000
  targetPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

  scaleDown:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30

  scaleUp:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30

hpa:
  name: attendance-app-hpa
  targetDeployment: attendance-app
