deployment:
  name: attendance-app
  namespace: attendance-app
  containerPort: 5000

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2

label: attendance-app

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: chimuanyavic7/attendance-app
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.1"



# Project namespace for your application
namespace: default

dbSecretName: db-secrets

DB_PASSWORD: AgAZyyj6h/nAPkvY7tJ24u79BVujYcvC0TsEgAzqpm8xZr4iJRk1fb5pX6P9aDMuf+MzVhzwoPGFZnbKH2EaM1yWR+lQMP6mE7gXdjH2gm3aDrZRUWJKeAebSkW+fEkx2eDmWhntUIkC+tnU+ws+JtdalOxglk2YB6VSoNC++D1dehrzHUqGHxHEKFj2R4fRvUvDdJ8yEfVoEQjRTZIZeYJ3TVSBTyJC3tAwxgswxFxWK3w4L+zlNJcNwZziKH5wNmiBMzHODUIAWHxGZkU1bzZntGpoTL2CIezG1tIC8jXr1PInZa7c7vzG/IrBQDugj8MWAJHZAyIbUORhE5bsFxDulLSIEVBXKmaiU524B7Bx/Wu8bCFEdItK9vI12+HT0A4Oo4Wo9hBuhB+CTtPC9RevqrRBxw/LLqWG6tyJcot4ssA821Lv9zarXimtNNU+CjMGaG1DgaJa5fN24sTgsqoucbdQJYErJ5wPTvcUhYE2UJC+/isUkLHx5+NbX6oVJnkODqanNm6+o1tNUpcU7nEsmJpj1nw+pOeXp5DNoa95ygEkxkAv/+GStZnrhBwj5Nwi2cr+oJwZKLCpB7voNz0XAFkE504nrNPjfrl+/YA+35K8Fm6KFYRFzS6okXs6jWXCXYzjnXRuhMSfN5lHQsTXZB9mwIHTyHrd1A2/FbD4G4f9itGxWpQ7dGZRb9nTu+3mvWAladw6ve+Cxw==

config:
  name: db-config
  DB_USER: "admin"
  DB_HOST: "172.17.0.2" 
  DB_PORT: "7001"
  DB_NAME: "postgres"

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  name: attendance-app-service
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: NodePort
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 5000
  targetPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

  scaleDown:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30

  scaleUp:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30

hpa:
  name: attendance-app-hpa
  targetDeployment: attendance-app
