deployment:
  name: attendance-app
  namespace: attendance-app
  containerPort: 5000

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2

label: attendance-app

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: chimuanyavic7/attendance-app
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.1"



# Project namespace for your application
namespace: attendance-app

dbSecretName: db-secrets

DB_PASSWORD: AgASoZ6q7ILqQiCyhwWJxSoQq22WUblwkBuVcr4muRsW0/4QJphNeLpIHLW1RQxNWGALCnrloaC1e/SGtLFrjPFu157hGvNNMyGZTBK2mtr7xewdA1QhoC4kgqDwYDGm9pYkOKzLCzmGvoNBnFQvrIR/JNVEZXTuaMQ0Ho0dwZiXyIxP6J0rgcnztB+naVZHcWlFqQuU06Widw4vX4+xce9E8yr5SxFY8F6ahZr9MwqUZ0pC3t97YiqDc3t5xmhiKTr/k2O2cmy1s/xzHKEu0eDe1A621KHpqINrKxj75VobND+3Y46J41tHN1fQHYVFb6wRi4s0FUd8qBqHhs5b/uoWqUd3SEStIMa9Ycw+mBnO8OZM/YRmcDkAgk4ujiJhDVQah13baQWJwHOK2Twjqa/buRp0KpA6hIpi/V/GAqItUbcPZNyHo38bZ8i9sgT4kLZ+RRKiol56lGOqqWOQVGqQJrH5gSHb8l+YxEefRsGQjfhpZjTzyDay2E6N3H8UVHRo9LN3UgRy6wRf0bY5qqgkiPF86E/ih/JLkcZUFek6qBgzTIsov68/l3Vp3Np40kgyZUHYmYBX5tvRO7gwXEBElmi/2nPKQlf7LEXvzlzE4a+i1QoUf5BmeBHwoOZyYH3/8BLntjNoZcF1BLBQKzDK+IdBl2Pczk4dCCmSNHvtJbSrAfwAcqqgqvEPPA1dGj56BRRcwGL4dWMbaA==

config:
  name: db-config
  DB_USER: "admin"
  DB_HOST: "172.17.0.2" 
  DB_PORT: "7002"
  DB_NAME: "postgres"

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  name: attendance-app-service
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: NodePort
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 5000
  targetPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
# autoscaling:
#  enabled: true
#  minReplicas: 2
#  maxReplicas: 10
#  targetCPUUtilizationPercentage: 70

#  scaleDown:
#    stabilizationWindowSeconds: 30
#    pods: 1
#    periodSeconds: 30

#  scaleUp:
#    stabilizationWindowSeconds: 30
#    pods: 1
#    periodSeconds: 30

# hpa:
#  name: attendance-app-hpa
#  targetDeployment: attendance-app


