name: Attendance App

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

# ==================================================
# SECURITY - GITLEAKS
# ==================================================

  gitleaks:
    name: Secret Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# ==================================================
# SEMANTIC VERSIONING
# ==================================================

  version:
    name: Semantic Version + Git SHA
    runs-on: ubuntu-latest
    needs: gitleaks

    outputs:
      version: ${{ steps.bump.outputs.version }}
      release: ${{ steps.bump.outputs.release }}
      sha: ${{ steps.commit.outputs.sha }}
      image_tag: ${{ steps.image_tag.outputs.image_tag }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Get latest version tag
        id: last_version
        run: |
          git fetch --tags

          LAST_TAG=$(git tag --sort=-v:refname | head -n 1)

          if [[ -z "$LAST_TAG" ]]; then
            LAST_TAG="v1.0.0"
          fi

          echo "last=$LAST_TAG" >> $GITHUB_OUTPUT


      - name: Get commit SHA
        id: commit
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT


      - name: Bump version
        id: bump
        run: |

          LAST=${{ steps.last_version.outputs.last }}
          VERSION=${LAST#v}

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          COMMIT_MESSAGE=$(git log -1 --pretty=%B)

          RELEASE=false


          if [[ "$COMMIT_MESSAGE" == major:* ]]; then

            MAJOR=$((MAJOR+1))
            MINOR=0
            PATCH=0
            RELEASE=true


          elif [[ "$COMMIT_MESSAGE" == minor:* ]]; then

            MINOR=$((MINOR+1))
            PATCH=0
            RELEASE=true


          elif [[ "$COMMIT_MESSAGE" == patch:* ]]; then

            PATCH=$((PATCH+1))
            RELEASE=true
          fi


          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "release=$RELEASE" >> $GITHUB_OUTPUT


      - name: Generate Docker Image Tag
        id: image_tag
        run: |
          VERSION=${{ steps.bump.outputs.version }}
          SHA=${{ steps.commit.outputs.sha }}

          IMAGE_TAG="${VERSION}-${SHA}"

          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT   


      - name: Create and push tag
        if: steps.bump.outputs.release == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump.outputs.version }}
          git push origin ${{ steps.bump.outputs.version }}




# ==================================================
# DOCKER BUILD
# ==================================================

  docker:

    name: Build & Push Image
    runs-on: ubuntu-latest
    needs: version

    env:
      IMAGE_TAG: ${{ needs.version.outputs.image_tag }}

    steps:

      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and Push Image
        uses: docker/build-push-action@v5

        with:
          context: .
          load: true
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}/attendance-app:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
# ==================================================
# IMAGE SECURITY SCAN
# ==================================================

#      - name: Security Scan (Trivy)
#        uses: aquasecurity/trivy-action@v0.33.1
#        with:
#          image-ref: ${{ env.IMAGE_NAME }}/attendance-app:${{ needs.version.outputs.image_tag }}        
#          format: "table"
#          exit-code: "1"
#          ignore-unfixed: true
#          vuln-type: "os,library"
#          severity: "CRITICAL,HIGH"


# ==================================================
# DOCKER PUSH IMAGE
# ==================================================

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image
        run: |
          docker push ${{ env.IMAGE_NAME }}/attendance-app:${{ env.IMAGE_TAG }}
    



# ==================================================
# HELM VALIDATION
# ==================================================

  validate:

    name: Validate Helm Chart
    runs-on: ubuntu-latest
    needs: [docker, version]
     
    steps:
      - uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4


      - name: Helm lint
        run: |
          helm lint helm/attendance-app-chart

      - name: Helm template test
        run: |
          helm template helm/attendance-app-chart \
            --set image.tag=${{ needs.version.outputs.image_tag }}



     

# ==================================================
# GITOPS UPDATE
# ==================================================

  gitops:
    name: Update Helm Values
    runs-on: ubuntu-latest
    needs: [validate, version]
      


    steps:
      - uses: actions/checkout@v4
      - name: Install yq
        uses: mikefarah/yq@v4.44.3


      - name: Update Helm Image Tag
        run: |
          IMAGE_TAG="${{ needs.version.outputs.image_tag }}"
          echo "Updating image tag to $IMAGE_TAG"
          yq eval -i ".image.tag = \"$IMAGE_TAG\"" helm/attendance-app-chart/values.yaml
           
           
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/attendance-app-chart/values.yaml
          if git diff --cached --quiet; then
            echo "No changes detected"
            exit 0
          fi
          git commit -m "deploy: ${{ needs.version.outputs.image_tag }}"
          git push origin main